In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# 1. Inladen van de dataset
df = pd.read_csv("groot_bestand.csv")

# 2. Basis info
print("ðŸ”¹ Shape:", df.shape)
print("ðŸ”¹ Kolommen:", df.columns.tolist())
print("\n--- INFO ---")
print(df.info())
print("\n--- Beschrijvende statistieken ---")
print(df.describe(include="all").transpose().head(20))

# 3. Missing values per kolom
print("\n--- Missing values ---")
print(df.isnull().sum().sort_values(ascending=False).head(20))

# 4. Distributie van numerieke variabelen (price, points)
df["points"].hist(bins=20, edgecolor="black")
plt.title("Verdeling punten (points)")
plt.xlabel("Points")
plt.ylabel("Aantal")
plt.show()

df["price"].dropna().hist(bins=50, edgecolor="black")
plt.title("Verdeling prijs (price)")
plt.xlabel("Prijs ($)")
plt.ylabel("Aantal")
plt.show()

# 5. TopcategorieÃ«n (country, variety)
print("\n--- Top 10 countries ---")
print(df["country"].value_counts().head(10))

print("\n--- Top 10 varieties ---")
print(df["variety"].value_counts().head(10))

# 6. Relatie tussen prijs en punten
print("\n--- Correlatie price-points ---")
print(df[["points", "price"]].corr())

df.plot.scatter(x="price", y="points", alpha=0.3)
plt.title("Relatie tussen prijs en punten")
plt.xlabel("Prijs ($)")
plt.ylabel("Punten")
plt.xlim(0, 500)  # uitschieters beperken
plt.show()

# 7. Tekstuele data verkennen (description)
df["desc_len"] = df["description"].str.len()
print("\n--- Lengte beschrijvingen ---")
print(df["desc_len"].describe())
df["desc_len"].hist(bins=50)
plt.title("Lengte van beschrijvingen")
plt.xlabel("Aantal karakters")
plt.ylabel("Aantal")
plt.show()

In [ ]:
# eerste rijen data
(df.head())

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,desc_len
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",VulkÃ Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin Oâ€™Keefe,@kerinokeefe,Nicosia 2013 VulkÃ Bianco (Etna),White Blend,Nicosia,172
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,227
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,186
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,199
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,249

In [ ]:
import pandas as pd

# Eerst bestand inladen (pas pad aan als nodig)
df = pd.read_csv("groot_bestand.csv")

# Nu controleren of er dubbele titles zijn
n_unique = df["title"].nunique()
n_total = len(df)

print(f"Totaal aantal rijen: {n_total}")
print(f"Aantal unieke titles: {n_unique}")
print(f"Duplicaten in titles: {n_total - n_unique}")

# Voorbeeld van titels die vaker dan 1 keer voorkomen
dupes = df["title"].value_counts()
print(dupes[dupes > 1].head(50))

Totaal aantal rijen: 129971
Aantal unieke titles: 118840
Duplicaten in titles: 11131
title
Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma County)                                         11
Korbel NV Brut Sparkling (California)                                                           9
Segura Viudas NV Extra Dry Sparkling (Cava)                                                     8
Segura Viudas NV Aria Estate Extra Dry Sparkling (Cava)                                         7
Gloria Ferrer NV Blanc de Noirs Sparkling (Carneros)                                            7
Ruinart NV Brut RosÃ©  (Champagne)                                                               7
Mumm Napa NV Brut Prestige Sparkling (Napa Valley)                                              6
Boizel NV Brut RÃ©serve  (Champagne)                                                             6
Pierre Sparr NV Brut RÃ©serve Sparkling (CrÃ©mant d'Alsace)                                       6
Bailly-Lapierre NV Brut  (CrÃ©mant de Bourgogne)                                                 6
Jacquart NV Brut MosaÃ¯que  (Champagne)                                                          6
J Vineyards & Winery NV Brut RosÃ© Sparkling (Russian River Valley)                              6
Korbel NV Sweet RosÃ© Sparkling (California)                                                     6
Mailly Grand Cru NV DÃ©lice Demi-Sec  (Champagne)                                                5
Jean Laurent NV Blanc de Noirs Brut Pinot Noir (Champagne)                                      5
Freixenet NV Cordon Negro Brut Sparkling (Cava)                                                 5
J. Dumangin Fils NV Le RosÃ© Premier Cru Brut  (Champagne)                                       5
Roederer Estate NV Brut RosÃ© Sparkling (Anderson Valley)                                        5
Chandon NV RosÃ© Sparkling (California)                                                          5
Henri Abele NV Brut  (Champagne)                                                                5
Freixenet NV Cordon Negro Extra Dry Sparkling (Cava)                                            5
G. H. Mumm NV Cordon Rouge Brut  (Champagne)                                                    5
ThiÃ©not NV Brut  (Champagne)                                                                    5
ThiÃ©not NV Brut RosÃ©  (Champagne)                                                               5
Heidsieck & Co Monopole NV Blue Top Brut  (Champagne)                                           5
Pommery NV Brut Royal  (Champagne)                                                              5
Mumm Napa NV CuvÃ©e M Sparkling (Napa Valley)                                                    5
Breathless NV Brut Sparkling (North Coast)                                                      5
Korbel NV Blanc de Noirs Sparkling (California)                                                 5
Segura Viudas NV Reserva Heredad Sparkling (Cava)                                               5
Mailly Grand Cru NV Blanc de Noirs Brut Pinot Noir (Champagne)                                  5
Villa Sandi NV Extra Dry  (Conegliano Valdobbiadene Prosecco Superiore)                         4
Pierre Gimonnet et Fils NV Cuis Premier Cru Blanc de Blancs Brut Chardonnay (Champagne)         4
Chandon NV Blanc de Noirs Sparkling (California)                                                4
Chanoine NV Tsarine CuvÃ©e Premium Brut  (Champagne)                                             4
Ferrari NV RosÃ© Sparkling (Trento)                                                              4
Louis Roederer NV Brut Premier  (Champagne)                                                     4
A.R. LenobleÂ  NV Intense Brut  (Champagne)                                                      4
Lanson NV Black Label Brut  (Champagne)                                                         4
Segura Viudas NV Aria Estate Brut Sparkling (Cava)                                              4
Ruinart NV Blanc de Blancs Brut Chardonnay (Champagne)                                          4
Taittinger NV Nocturne Sec  (Champagne)                                                         4
Segura Viudas NV Brut Reserva Sparkling (Cava)                                                  4
Terre di San Venanzio Fortunato NV Extra Dry  (Conegliano Valdobbiadene Prosecco Superiore)     4
Bodegas Dios Baco S.L. NV Amontillado Sherry (Jerez)                                            4
Nicolas Feuillatte NV Brut RosÃ©  (Champagne)                                                    4
Mumm Napa NV Brut RosÃ© Sparkling (Napa Valley)                                                  4
Nicolas Feuillatte NV Brut  (Champagne)                                                         4
Korbel NV Extra Dry Sparkling (California)                                                      4
Vollereaux NV Brut RÃ©serve  (Champagne)                                                         4
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Eerst bestand inladen (pas pad aan als nodig)
df = pd.read_csv("groot_bestand.csv")

# Nu controleren of er dubbele titles zijn
n_unique = df["taster_name"].nunique()
n_total = len(df)

print(f"Totaal aantal rijen: {n_total}")
print(f"Aantal unieke titles: {n_unique}")
print(f"Duplicaten in titles: {n_total - n_unique}")

# Voorbeeld van titels die vaker dan 1 keer voorkomen
dupes = df["taster_name"].value_counts()
print(dupes[dupes > 0].head(50))

Totaal aantal rijen: 129971
Aantal unieke titles: 19
Duplicaten in titles: 129952
taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin Oâ€™Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne KrebiehlÂ MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Eerst bestand inladen (pas pad aan als nodig)
df = pd.read_csv("groot_bestand.csv")

# Nu controleren of er dubbele titles zijn
n_unique = df["country"].nunique()
n_total = len(df)

print(f"Totaal aantal rijen: {n_total}")
print(f"Aantal unieke titles: {n_unique}")
print(f"Duplicaten in titles: {n_total - n_unique}")

# Voorbeeld van titels die vaker dan 1 keer voorkomen
dupes = df["country"].value_counts()
print(dupes[dupes > 1].head(50))

Totaal aantal rijen: 129971
Aantal unieke titles: 43
Duplicaten in titles: 129928
country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedonia                    12
Czech Republic               12
Serbia                       12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Laad je bestand (pas pad aan als nodig)
df = pd.read_csv("groot_bestand.csv")

# Kleine check
print(df.head(3))